version: "3"

services:
  api:
    build:
      context: api/
      dockerfile: Dockerfile

    environment:
      RABBITMQ_CONNECTION_URI: "amqp://root:T7b9eEHLpxqLnAdb@rabbit:5672/%2F"

    command: "uvicorn app.main:app --host 0.0.0.0 --port 80"

    depends_on:
      - rabbit

  telegram:
    build:
      context: telegram/
      dockerfile: Dockerfile

    environment:
      TELEGRAM_TOKEN: "1267664941:AAHSehVcBdjTPiIjVtnxgxiMnn9f1hqlKyw"
      GAYBUSTER_URL: "http://api/detect/"

    command: "python -m app"

  rabbit:
    image: rabbitmq:3.8.2

    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: T7b9eEHLpxqLnAdb

    ports:
      - 5672:5672