version: "3"

services:
  api:
    build:
      context: api/
      dockerfile: Dockerfile

    environment:
      RABBITMQ_CONNECTION_URI: "amqp://root:T7b9eEHLpxqLnAdb@rabbit:5672/%2F"

    command: "uvicorn app.main:app --host 0.0.0.0 --port 80"

    depends_on:
      - rabbit

  telegram:
    build:
      context: telegram/
      dockerfile: Dockerfile

    environment:
      TELEGRAM_TOKEN: "1254301929:AAHt7tN4ZJrv6-wH7kS5kA1Rcw-G3SM4EXI"
      GAYBUSTER_API_URL: "http://api/detect/"
      POSTGRES_CONNECTION_URI: 'postgres://postgres:root@database:5432/gaybuster'

    command: "python -m app"

    volumes:
      - ./data/telegram_detections/:/detections/

  rabbit:
    image: rabbitmq:3.8.2

    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: T7b9eEHLpxqLnAdb

    ports:
      - 5672:5672

  database:
    image: postgres:12.1-alpine

    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gaybuster

    volumes:
      - ./data/pgdata:/var/lib/postgresql/data

    ports:
      - 5432:5432
